version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  open-pull-requests-limit: 10
  reviewers:
    - denday04
  assignees:
    - denday04
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
