name: cd

on:
  push:
    branches:
      - release

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: master
          force_orphan: true      # don't keep history of publish commits on branch - only keep latest
          commit_message: 'Automated CD release'
          user_name: 'github-actions[bot]'                            # display bot author instead of actual
          user_email: 'github-actions[bot]@users.noreply.github.com'  # display bot author instead of actual
